name: Check Domain Registry & SSL

on:
  schedule:
    - cron:  '30 * * * *'
  workflow_dispatch:

permissions:
  contents: read
  issues: write

jobs:
  check_registry:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    name: Check Registry

    steps:
      - name: Check domain registry expire date
        id: check-domain
        uses: cuteio/domain-monitor@main
        with:
          domains: |
            douban.com
            x.com
            ccluster.net
          check-type: registry
          warning-days: 800
          github-token: ${{ secrets.GITHUB_TOKEN }}
          assignee: liluo


  check_ssl:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    name: Check ssl

    steps:
      - name: Check domain registry expire date
        id: check-domain
        uses: cuteio/domain-monitor@main
        with:
          domains: |
            douban.com
            x.com
            zero-homers.ccluster.net
          check-type: ssl
          warning-days: 900
          github-token: ${{ secrets.GITHUB_TOKEN }}
          assignee: liluo


